---
repo-name: peripherals-ms-azure
categories:
- Cloud
- DevOps
display-name: Microsoft Azure
description: Microsoft Azure is a cloud computing service created by Microsoft for building, deploying, and managing applications and services through a global network of Microsoft-managed data centers
manufacturer: Microsoft
